### ISSUE TITLE
Copying files to AOS6 devices?

### ISSUE THREAD

**Issue by cs-1** [gmoisio/ansible-aos-stdlib#4]
Hi!

I was wondering if there was any way to copy files to AOS6 devices using ansible-aos-stdlib. I've tried using the standard copy module but wasn't successful with either "connection: ssh" nor "connection: paramiko_ssh" so I was hoping to be able to do this via ansible-aos-stdlib.

Cheers,
Christian

**Comment by gmoisio** [comment]
Hi, thank you for your message.
The role ansible-aos-stdlib has no builtin copy feature. It can run a command on the switch to copy file if this one is on a file server.
The issue your are facing with standard copy module is perhaps an SSH one with AOS6.
Try to put something like that in ~/.ssh/config file to test on a switch:

```
Host xx.yy.zz.ww
    HostKeyAlgorithms +ssh-dss
```

If you want, you can add a more global setting in /etc/ssh/ssh_config:

```
Host *
HostkeyAlgorithms +ssh-dss
PubkeyAcceptedKeyTypes +ssh-dss
MACs hmac-sha1
```

Keep in mind that ssh_config is a configuration file dedicated to OpenSSH tools, but not available to SSH outside those cases, so try to find how to take into account the settings in your case.

Regards

**Comment by cs-1** [comment]
Hi Gilbert,

thanks for your speedy reply. I agree that using a command on AOS to copy the file seems to be the best option for now.

Christian
