### ISSUE TITLE
Feature request: return diff

### ISSUE THREAD

**Issue by cs-1** [gmoisio/ansible-aos-stdlib#6]
Hi all!

I have a feature request: when running ale_aos_config the module itself uses a "diff" between two configuration snapshots to determine whether or not something changed. Would it be possible to return the differences in some sort of unified diff format or similar so that they can be used in debugging?

Kind regards,
Christian

**Comment by gmoisio** [comment]
Hi, thank you for your contact.
I will have a look at this feature to see what can be done.
Regards

**Comment by gmoisio** [comment]
A new feature as been added in configuration module and you can use it as a tip with your playbook using:

ansible-playbook myplaybook --diff -v

Best Regards

**Comment by cs-1** [comment]
Hi Gilbert!

That's fantastic! I'll check it out ASAP!

Christian

**Comment by gmoisio** [comment]
Feature implemented
